# Site settings
title: Open Source is Tech Transfer
tagline: "Making the case that open source software is a form of technology transfer"
author:
  name: Andrew Wichmann
  email: andrew.wichmann@gmail.com
description: "Resources for understanding open source software as technology transfer â€” for researchers, institutions, and policymakers."
url: "https://ositt.org"
baseurl: ""

# SEO & social
lang: en
timezone: America/New_York

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
